---

caddy_tls_providers:
  - provider: cloudflare
    challenge_type: dns
    provider_api_token: "{{ cloudflare_api_token }}"
    resolver_ip: 1.1.1.1

caddy_endpoints:
  - friendly_name: jf
    fqdn: jf.amireally.online
    upstream: "truenas-scale:8096"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: abs
    fqdn: abs.amireally.online
    upstream: "truenas-scale:30067"
    tls_insecure: false
    tls_provider: cloudflare
  - friendly_name: pocket-id
    fqdn: oidc.amireally.online
    upstream: "truenas-scale:30218"
    tls_insecure: false
    tls_provider: cloudflare